### ISSUE TITLE
EasySend Polish

### ISSUE THREAD

**Issue by ferrerrajc** [meritlabs/lightwallet-stack#147]
## outstanding easySend issues
- [ ] deeplink causes home screen to prompt for easyReceive password even after transaction has been redeemed.
- [ ] lightwallet _sometimes_ prints the error: `Cannot read property 'credentials' of undefined` to console on transition to confirm page, with no indication that something has failed on the app.

## easySend improvements
- [x] User should be able to enter a phone number or email address (not matching an existing contact) on the send tab for an easySend transaction #136 
- [ ] User should be able to see and change the sending method that will be used while on the amount page
- [ ] User should be able to re-send or cancel pending easySend transactions from the home page. #142 
- [ ] User should be able to enter an optional password when creating an easySend transaction
- [ ] User should be able to select the timeout for an easySend transaction
- [x] When a recipient rejects an easysend transaction, the merit should be returned to the sender. #148
