### ISSUE TITLE
Can send a beacon via the lightwallet to the merit test network.

### ISSUE THREAD

**Issue by taywils** [meritlabs/lightwallet-stack#4]
## Description
From the merit lightwallet app we need the ability to notify the Merit test network by sending a beacon. This should be accomplished interactively by using the app and capturing the response on the Merit Bitcoin app (for now in a log output is fine).

### Tasks
- [ ] Update any UI on the lightwallet if necessary
- [ ] Config the lightwallet and bitcore-node to use Merit test net
- [ ] Add/Update any code in the lightwallet-stack to send RPC to Merit test net
