### ISSUE TITLE
[Meta] E2E Testing for Core UX Flows

### ISSUE THREAD

**Issue by adilwali** [meritlabs/lightwallet-stack#650]
Now that FF2 is out, and we are nearing Wildfire, we need stronger E2E testing to have confidence when we make changes to DLW, MLW, and DNW.  

We should cover: 

- [x] Unlock Flow for new users
- [ ] EasyReceive flow for existing users
- [ ] EasyReceive flow for new users
- [x] GlobalSend flow
- [x] Regular (classic) send flow
