### ISSUE TITLE
[Meta] More test coverage for DLW, MLW, and DNW.

### ISSUE THREAD

**Issue by adilwali** [meritlabs/lightwallet-stack#651]
We should get to a place where core UI code has strong coverage for all "LightWallets".  We should target the code that powers the most robust and active use cases:
 
- [x] Unlock experience for new users
- [ ] EasyReceive experience for new users
- [x] EasyReceive experience for existing users
- [x] GlobalSend experience
- [x] Regular (classic) send experience
